default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: my_factory_bot
  host: 127.0.0.1

development:
  <<: *default
  database: my_factory_bot_development

test:
  <<: *default
  database: my_factory_bot_test

production:
  <<: *default
  database: my_factory_bot_production
  username: my_factory_bot
  password:
